import Head from 'next/head'
import React from 'react'
import useSWR from 'swr'
import styles from '../styles/Home.module.css'
import { Flex, Text, Spacer, Input, Button } from "@chakra-ui/react"
import shortid from 'shortid';
import Encuesta from '../components/Encuesta'

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Home() {
  const [encuesta, setEncuesta] = React.useState({id:"", titulo:"", descripcion:""})
  const {data, error} = useSWR('/api/encuestas', fetcher)

  if (error) return <div>Failed to load users</div>
  if (!data) return <div>Loading...</div>

  const agregarEncuesta = (e) => {
    e.preventDefault();
    if(!encuesta.titulo){
        console.log('Elemento vacio')
        return
    }
    data.push({id: shortid.generate(), titulo: encuesta.titulo, descripcion: encuesta.descripcion})
    setEncuesta({id:"", titulo:"", descripcion:""})
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Encuesta Vrava</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Encuesta de satisfacción del cliente
        </h1>

        <Flex m="10" direction='column'>
          <Text>Ingrese el título</Text>
          <Flex mt='2'>
              <Input 
              placeholder="Título" 
              value={encuesta.titulo} 
              onChange={e => setEncuesta({...encuesta, titulo: e.target.value})}/>
          </Flex>
          <Text mt='2'>Ingrese la descripción</Text>
          <Flex mt='2'>
              <Input 
              placeholder="Descripción" 
              value={encuesta.descripcion} 
              onChange={e => setEncuesta({...encuesta, descripcion: e.target.value})}/>
          </Flex>
          <Button mt='2' colorScheme="teal" onClick={agregarEncuesta}>Agregar</Button>
        </Flex>

        <p className={styles.description}>
          Lista de encuestas
        </p>
        <Flex m="10">
          <ul>
            {
              data.length === 0 ? (<li>No hay Encuestas</li>) : (
                  data.map(item => (
                    <Encuesta encuesta={item} key={item.id}/>
                  ))
              )
            }
          </ul>
        </Flex>
      </main>

    </div>
  )
}
